---
environment_repo: &environment_repo git@github.com:your-org/your-repo.git
environment_dir: &environment_dir azure/environments
environment_name: &environment_name mycoolenvironment
system_domain: &sys_domain mycoolenvironment.example.com
devbox_username: &devbox_username myuser
git_email: &git_email my_github_email@example.com
git_name: &git_name myuser
github_key: &github_key {{github-key}}
worker_tag: &worker_tag []
azure_region: &azure_region "West US"
azure_subscription: &azure_subscription {{azure_subscription}}
azure_tenant_id: &azure_tenant_id {{azure_tenant_id}}
azure_client_id: &azure_client_id {{azure_client_id}}
azure_client_secret: &azure_client_secret {{azure_client_secret}}
aws_shared_dns_access_key: &aws_shared_dns_access_key {{aws-shared-dns-access-key}}
aws_shared_dns_access_secret: &aws_shared_dns_access_secret {{aws-shared-dns-access-secret}}
aws_route53_zone_id: &aws_route53_zone_id Z1OE08QT9BJFFU  # this is cf-app.com
ssl_countryname: &ssl_countryname "US"
ssl_state: &ssl_state "California"
ssl_locality: &ssl_locality "San Francisco"
ssl_org: &ssl_org "Pivotal"
ssl_org_unit: &ssl_org_unit "Cloud Foundry"
ssl_subdomain: &ssl_subdomain "cf-app.com"

groups:
- name: bootstrap-azure
  jobs:
  - bootstrap-environment
  - setup-devbox-upload-bosh-yml
- name: deploy-cf-azure
  jobs:
  - deploy-bosh-generate-upload-deployment-ymls
  - deploy-mysql
  - deploy-cf
  - deploy-diego
- name: destroy-cf-azure
  jobs:
  - destroy-bosh-deployments
  - destroy-bosh-director
  - destroy-azure-resource-group

resources:
  - name: azure_environments
    type: git
    source:
      uri: *environment_repo
      branch: master
      private_key: *github_key
  - name: toolsmiths-shared-scripts
    type: git
    source:
      uri: https://github.com/pivotal-cf/toolsmiths-shared-scripts

jobs:
  - name: bootstrap-environment
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
    - task: create-environment
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        outputs:
        - name: environment
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_terraform.sh -d ${ENV_DIR}/${ENV_NAME} apply"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir
        DEVBOX_USERNAME: *devbox_username
        AZURE_REGION: *azure_region
        AZURE_SUBSCRIPTION: *azure_subscription
        AZURE_TENANT_ID: *azure_tenant_id
        AZURE_CLIENT_ID: *azure_client_id
        AZURE_CLIENT_SECRET: *azure_client_secret
        AWS_SHARED_DNS_ACCESS_KEY: *aws_shared_dns_access_key
        AWS_SHARED_DNS_ACCESS_SECRET: *aws_shared_dns_access_secret
        AWS_ROUTE53_ZONE_ID: *aws_route53_zone_id
        GIT_EMAIL: *git_email
        GIT_NAME: *git_name
        SYSTEM_DOMAIN: *sys_domain
      ensure:
        put: azure_environments
        params:
          repository: environment
          rebase: true

  - name: setup-devbox-upload-bosh-yml
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
        passed: [bootstrap-environment]
    - task: setup-devbox-upload-bosh-yml
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_setup_dev_box.sh azure_environments/${ENV_DIR}/${ENV_NAME}"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir

  - name: deploy-bosh-generate-upload-deployment-ymls
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
    - task: deploy-bosh-and-generate-ymls
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        outputs:
        - name: environment
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_deploy_bosh_generate_ymls.sh $ENV_DIR/$ENV_NAME"]
      params:
        GIT_EMAIL: *git_email
        GIT_NAME: *git_name
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir
        SSL_COUNTRYNAME: *ssl_countryname
        SSL_STATE: *ssl_state
        SSL_LOCALITY: *ssl_locality
        SSL_ORG: *ssl_org
        SSL_ORG_UNIT: *ssl_org_unit
        SSL_SUBDOMAIN: *ssl_subdomain
    - put: azure_environments
      params:
        repository: environment
        rebase: true

  - name: deploy-mysql
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
        passed: [deploy-bosh-generate-upload-deployment-ymls]
        trigger: true
    - task: deploy-mysql
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh deployment ~/mysql.yml && bosh -n deploy'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir

  - name: deploy-cf
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
        passed: [deploy-mysql]
        trigger: true
    - task: deploy-cf
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh deployment ~/cf.yml && bosh -n deploy'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir

  - name: deploy-diego
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
        passed: [deploy-cf]
        trigger: true
    - task: deploy-diego
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh deployment ~/diego.yml && bosh -n deploy'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir

  - name: destroy-bosh-deployments
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
    - task: destroy-diego-deployment
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh -n delete deployment diego --force'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir
    - task: destroy-cf-deployment
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh -n delete deployment cf --force'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir
    - task: destroy-mysql-deployment
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh -n delete deployment mysql --force'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir

  - name: destroy-bosh-director
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
        passed: [destroy-bosh-deployments]
    - task: destroy-bosh-director
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh-init delete ~/bosh.yml'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir

  - name: destroy-azure-resource-group
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
        passed: [destroy-bosh-director]
    - task: destroy-azure-resource-group
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        outputs:
        - name: environment
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_terraform.sh -d ${ENV_DIR}/${ENV_NAME} destroy"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir
        DEVBOX_USERNAME: *devbox_username
        AZURE_REGION: *azure_region
        AZURE_SUBSCRIPTION: *azure_subscription
        AZURE_TENANT_ID: *azure_tenant_id
        AZURE_CLIENT_ID: *azure_client_id
        AZURE_CLIENT_SECRET: *azure_client_secret
        AWS_SHARED_DNS_ACCESS_KEY: *aws_shared_dns_access_key
        AWS_SHARED_DNS_ACCESS_SECRET: *aws_shared_dns_access_secret
        AWS_ROUTE53_ZONE_ID: *aws_route53_zone_id
        GIT_EMAIL: *git_email
        GIT_NAME: *git_name
        SYSTEM_DOMAIN: *sys_domain
      ensure:
        put: azure_environments
        params:
          repository: environment
          rebase: true
