---
opsmgr_version: &opsmgr_version 1.7.7
ert_version: &ert_version 1.7.6
environment_name: &env_name stormwind
env_app_url: &env_app_url environments.toolsmiths.cf-app.com
pivnet_token: &pivnet_token {{pivnet-token}}
worker_tag: &worker_tag [vsphere]
github_key: &github_key {{github-key}}
download_retry_attempts: &retry 3

groups:
- name: deploy-pcf-vsphere
  jobs:
  - upload-om-pcf-vsphere
  - configure-ops-manager
  - upload-elastic-runtime-pcf-vsphere
  - configure-elastic-runtime
  - trigger-install

resources:
  - name: toolsmiths-shared-scripts
    type: git
    source:
      uri: https://github.com/pivotal-cf/toolsmiths-shared-scripts
  - name: p-runtime
    type: git
    source:
      uri: git@github.com:pivotal-cf/p-runtime.git
      private_key: *github_key
      branch: dev/1.8

jobs:
  - name: upload-om-pcf-vsphere
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: p-runtime
    - task: download-ops-manager-from-pivnet
      attempts: *retry
      tags: *worker_tag
      privileged: true
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-pcf-vsphere
        inputs:
        - name: toolsmiths-shared-scripts
        outputs:
        - name: pivnet-downloads
        run:
          path: /bin/bash
          args: ['-c', 'export BUNDLE_GEMFILE=${PWD}/toolsmiths-shared-scripts/deploy_pcf/Gemfile && pushd pivnet-downloads && bundle install && bundle exec ../toolsmiths-shared-scripts/deploy_pcf/download-from-pivnet.rb -o']
      params:
        PIVNET_TOKEN: *pivnet_token
        OPSMGR_VERSION: *opsmgr_version
    - task: get-env-config
      tags: *worker_tag
      privileged: true
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-pcf-vsphere
        outputs:
        - name: environment
        run:
          path: /bin/bash
          args: ['-c', 'echo "Downloading manifest for resource_pool: ${ENV_NAME} from environment app: http://${ENV_APP_URL}" && wget http://${ENV_APP_URL}/engineering_environments/${ENV_NAME}/generate_with_name -O ${ENV_NAME}.yml']
          dir: environment
      params:
        ENV_NAME: *env_name
        ENV_APP_URL: *env_app_url
    - task: deploy-ops-manager
      tags: *worker_tag
      privileged: true
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-pcf-vsphere
        inputs:
        - name: toolsmiths-shared-scripts
        - name: pivnet-downloads
        - name: environment
        - name: p-runtime
        run:
          path: /bin/bash
          args: ['-c', 'bundle install && ./deploy_pcf.rb -D ../../environment -N ${ENV_NAME} -O $(ls ../../pivnet-downloads/*.ova) -H -C opsmgr:destroy,opsmgr:install']
          dir: toolsmiths-shared-scripts/deploy_pcf
      params:
        ENV_NAME: *env_name
        OPSMGR_VERSION: *opsmgr_version
  - name: configure-ops-manager
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: p-runtime
        passed: [upload-om-pcf-vsphere]
        trigger: true
    - task: get-env-config
      tags: *worker_tag
      privileged: true
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-pcf-vsphere
        outputs:
        - name: environment
        run:
          path: /bin/bash
          args: ['-c', 'echo "Downloading manifest for resource_pool: ${ENV_NAME} from environment app: http://${ENV_APP_URL}" && wget http://${ENV_APP_URL}/engineering_environments/${ENV_NAME}/generate_with_name -O ${ENV_NAME}.yml']
          dir: environment
      params:
        ENV_NAME: *env_name
        ENV_APP_URL: *env_app_url
    - task: configure-ops-manager
      tags: *worker_tag
      privileged: true
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-pcf-vsphere
        inputs:
        - name: p-runtime
        - name: toolsmiths-shared-scripts
        - name: environment
        run:
          path: /bin/bash
          args: ['-c', 'bundle && ./deploy_pcf.rb -D ../../environment -N ${ENV_NAME} -H -C opsmgr:add_first_user,opsmgr:microbosh:configure']
          dir: toolsmiths-shared-scripts/deploy_pcf
      params:
        ENV_NAME: *env_name
        OPSMGR_VERSION: *opsmgr_version
        PIVNET_TOKEN: *pivnet_token
  - name: upload-elastic-runtime-pcf-vsphere
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: p-runtime
        passed: [configure-ops-manager]
        trigger: true
    - task: download-elastic-runtime-from-pivnet
      attempts: *retry
      tags: *worker_tag
      privileged: true
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-pcf-vsphere
        inputs:
        - name: toolsmiths-shared-scripts
        outputs:
        - name: pivnet-downloads
        run:
          path: /bin/bash
          args: ['-c', 'export BUNDLE_GEMFILE=${PWD}/toolsmiths-shared-scripts/deploy_pcf/Gemfile && pushd pivnet-downloads && bundle install && bundle exec ../toolsmiths-shared-scripts/deploy_pcf/download-from-pivnet.rb -e']
      params:
        PIVNET_TOKEN: *pivnet_token
        ERT_VERSION: *ert_version
    - task: get-env-config
      tags: *worker_tag
      privileged: true
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-pcf-vsphere
        outputs:
        - name: environment
        run:
          path: /bin/bash
          args: ['-c', 'echo "Downloading manifest for resource_pool: ${ENV_NAME} from environment app: http://${ENV_APP_URL}" && wget http://${ENV_APP_URL}/engineering_environments/${ENV_NAME}/generate_with_name -O ${ENV_NAME}.yml']
          dir: environment
      params:
        ENV_NAME: *env_name
        ENV_APP_URL: *env_app_url
    - task: upload-elastic-runtime
      tags: *worker_tag
      privileged: true
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-pcf-vsphere
        inputs:
        - name: toolsmiths-shared-scripts
        - name: pivnet-downloads
        - name: environment
        - name: p-runtime
        run:
          path: /bin/bash
          args: ['-c', 'bundle install && ./deploy_pcf.rb -D ../../environment -N ${ENV_NAME} -E $(ls ../../pivnet-downloads/*.pivotal) -H -C opsmgr:product:upload_add,opsmgr:product:import_stemcell']
          dir: toolsmiths-shared-scripts/deploy_pcf
      params:
        ENV_NAME: *env_name
        OPSMGR_VERSION: *opsmgr_version
        PIVNET_TOKEN: *pivnet_token
  - name: configure-elastic-runtime
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: p-runtime
        passed: [upload-elastic-runtime-pcf-vsphere]
        trigger: true
    - task: get-env-config
      tags: *worker_tag
      privileged: true
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-pcf-vsphere
        outputs:
        - name: environment
        run:
          path: /bin/bash
          args: ['-c', 'echo "Downloading manifest for resource_pool: ${ENV_NAME} from environment app: http://${ENV_APP_URL}" && wget http://${ENV_APP_URL}/engineering_environments/${ENV_NAME}/generate_with_name -O ${ENV_NAME}.yml']
          dir: environment
      params:
        ENV_NAME: *env_name
        ENV_APP_URL: *env_app_url
    - task: configure-elastic-runtime
      tags: *worker_tag
      privileged: true
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-pcf-vsphere
        inputs:
        - name: toolsmiths-shared-scripts
        - name: environment
        - name: p-runtime
        run:
          path: /bin/bash
          args: ['-c', 'bundle install && ./deploy_pcf.rb -D ../../environment -N ${ENV_NAME} -H -C ert:configure']
          dir: toolsmiths-shared-scripts/deploy_pcf
      params:
        ENV_NAME: *env_name
        OPSMGR_VERSION: *opsmgr_version
        ERT_VERSION: *ert_version
        PIVNET_TOKEN: *pivnet_token
  - name: trigger-install
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: p-runtime
        passed: [configure-elastic-runtime]
        trigger: true
    - task: get-env-config
      tags: *worker_tag
      privileged: true
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-pcf-vsphere
        outputs:
        - name: environment
        run:
          path: /bin/bash
          args: ['-c', 'echo "Downloading manifest for resource_pool: ${ENV_NAME} from environment app: http://${ENV_APP_URL}" && wget http://${ENV_APP_URL}/engineering_environments/${ENV_NAME}/generate_with_name -O ${ENV_NAME}.yml']
          dir: environment
      params:
        ENV_NAME: *env_name
        ENV_APP_URL: *env_app_url
    - task: trigger-install
      tags: *worker_tag
      privileged: true
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-pcf-vsphere
        inputs:
        - name: toolsmiths-shared-scripts
        - name: environment
        - name: p-runtime
        run:
          path: /bin/bash
          args: ['-c', 'bundle install && ./deploy_pcf.rb -D ../../environment -N ${ENV_NAME} -H -C opsmgr:trigger_install']
          dir: toolsmiths-shared-scripts/deploy_pcf
      params:
        ENV_NAME: *env_name
        OPSMGR_VERSION: *opsmgr_version
        PIVNET_TOKEN: *pivnet_token
